export type { CustomError, IGenre, IPerson } from './responses'
export type { IFilm, IMovieRes, IMovies } from './film'
export type { IRegister } from './forms'
export type { IIncome } from './income'
export type { INews } from './news'
export type { registerSchemas, ILoginFields, loginSchema } from './schemas'
export type { IVideo } from './video'
export type { IHeroSlide } from './heroSlider'
