export { Main } from './Main/Main'
export { NotFound } from './NotFound/NotFound'
export { Premiere } from './Premiere/Premiere'
export { FilmPage } from './FilmPage/FilmPage'
export { News } from './News/News'
export { OneNews } from './OneNews/OneNews'
export { Collections } from './Collections/Collections'
export { ChosenCollection } from './Collections/subpages/ChosenCollection'
export { SearchResult } from './SearchResult/SearchResult'
export { Profile } from './Profile/Profile'
export { ProfileMain } from './Profile/subpages/ProfileMain/ProfileMain'
export { Setting as ProfileSetting } from './Profile/subpages/Setting/Setting'
export { UserReviews } from './Profile/subpages/UserReviews/UserReviews'
export { Friends } from './Profile/subpages/Friends/Friends'
export { Likes } from './Profile/subpages/Likes/Likes'
export { Actors } from './Actors/Actors'
export { Actor, loadActor } from './Actor/Actor'
